### ISSUE TITLE
There are no hand palm and foot 

### ISSUE THREAD

**Issue by SwapnilNSDN** [HichamELBSI/react-native-body-highlighter#10]
Need hand palm and Foot in svg image so we can click all parts of human body

**Comment by hanishsharma31** [comment]
Same requirement :D

**Comment by HichamELBSI** [comment]
Drum roll, please! 🥁 The moment you've all been waiting for is here – the react-native-body-highlighter update extravaganza! We've added hands, ankles, and feet, and guess what? Our human body model just got a major glow-up! It might have taken us a while, but hey, even a fine wine needs its time, right?
