### ISSUE TITLE
Error while toggle the body

### ISSUE THREAD

**Issue by Shahrukh0396** [HichamELBSI/react-native-body-highlighter#26]
<img width="334" alt="Screen Shot 2022-10-21 at 12 58 32 AM" src="https://user-images.githubusercontent.com/33844214/197045834-7d75e5ea-2188-429b-b90b-7d81ae5d794a.png">

<img width="705" alt="Screen Shot 2022-10-21 at 12 55 57 AM" src="https://user-images.githubusercontent.com/33844214/197045882-b05d60f3-1fa1-4943-a08f-2ead91fdf6cb.png">

**Comment by saurabh-c-kipl** [comment]
Facing the same issue, Is there any solution for this ?

**Comment by minelarka14** [comment]
What I did was remove the left hand and right hand muscle groups from `bodyBack.ts` and it seems to remove the issue for me. I'm not too sure if the left and right hands were originally viewable as noted from  Issue #10, so you might want to try this fix out.

![Screenshot 2022-11-21 at 19 07 26](https://user-images.githubusercontent.com/67103516/203035519-46a5fab3-457b-4f76-9028-40fbdcd742fc.png)

**Comment by HichamELBSI** [comment]
Hi @Shahrukh0396  Thanks for reporting this issue, it should be fixed now. Sorry for the late answer.
Thanks to @minelarka14
