### ISSUE TITLE
The app app crashed with {"rootTag":1}

### ISSUE THREAD

**Issue by unai8** [HichamELBSI/react-native-body-highlighter#27]
When i put the body object, I get the following error
![image](https://user-images.githubusercontent.com/74474876/197411909-bc4a3af8-95cd-4346-a1bc-d4d21c6c1e7f.png)
And the application closes
This is the code:
![image](https://user-images.githubusercontent.com/74474876/197411986-390dda87-2823-4f03-a315-11323cb85d5d.png)
Thanks

**Comment by HichamELBSI** [comment]
Hi @unai8 Thanks for reporting this issue, it should be fixed now. Sorry for the late answer.
