### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by jaliuson** [HichamELBSI/react-native-body-highlighter#34]
Invariant violation occurs when trying to render diagram. Worked on previous version (v2.1.0) with fix from issue #26 
![VSCode Error](https://user-images.githubusercontent.com/45365076/205469893-a42ede5c-931b-457c-b90a-c7c342bc1ae1.JPG)
![Emulator Error](https://user-images.githubusercontent.com/45365076/205469897-09d08552-c3e8-488f-91f8-c447524dd542.JPG)

**Comment by HichamELBSI** [comment]
Hello, @jaliuson it should be fixed in the 2.1.4 Feel free to re-open it if not.
