### ISSUE TITLE
Invariant violation: Tried to register two views with the same name RNSVGRect

### ISSUE THREAD

**Issue by yomiAdenaike01** [HichamELBSI/react-native-body-highlighter#4]
Code snippet: 
`<Body onMusclePress={(bodyPart) => handleUpdateBody(bodyPart)} />`

![Capture](https://user-images.githubusercontent.com/20516914/86190657-d12c6180-bb3c-11ea-9516-fee438231e05.PNG)

**Comment by HichamELBSI** [comment]
Hello, I can't reproduce the issue. Can you clarify please?

**Comment by pooooriya** [comment]
same issue I have
