### ISSUE TITLE
switch to woman?

### ISSUE THREAD

**Issue by megacherry** [HichamELBSI/react-native-body-highlighter#49]
First of all, thank you very much for your efforts.

Is it possible to use a woman in addition to a man?

I could extend this myself, but I'm not very familiar with vector graphics.

Many thanks in advance.

**Comment by HichamELBSI** [comment]
Hello, thanks for your feedback, I'm currently working on it, it will be released soon.

**Comment by HichamELBSI** [comment]
I'm glad to annouce that the new 3.0.0-beta.5 include the male and female body SVGs. Please consider this as a beta work in progress.
