### ISSUE TITLE
how to select only one part of the body. it selects pair. 

### ISSUE THREAD

**Issue by Kashifmub205** [HichamELBSI/react-native-body-highlighter#51]
is there any way to select only one part of the body by default it selects the pair of the part i.e. if I want to select the left shoulder it should only select the left shoulder. currently, it selects both shoulders.

**Comment by HichamELBSI** [comment]
Not yet unfortunately. Feel free to create a PR if you think you can work on it.

**Comment by sqb47** [comment]
i have figured out how to do this functionality
we basically have to define path array of left and right body separately, but separating it requires some manual work manual work.
i will create a PR soon

**Comment by HichamELBSI** [comment]
Hello, happy to share with you that this is now part of the new version `3.1.0` feel free to try it.
