### ISSUE TITLE
crashes app when including Body

### ISSUE THREAD

**Issue by Drivez** [HichamELBSI/react-native-body-highlighter#53]
I am using Expo to build the app. It works fine in the simulator for both iOS and Android, but building it and opening a page with the Body component crashes the app.
tested 3.0.0-beta.4 and beta.6
Not sure if this is related to 'react-native-svg' bug i have been reading up on.

**Comment by mphill** [comment]
It’s working for me with Expo. Can you get sentry setup and try to capture some diagnostic information?

**Comment by Drivez** [comment]
i will add it now and do a rebuild

**Comment by Drivez** [comment]
Added Sentry to the app and now I froze on loding with `Invariant Violation
requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager. `

**Comment by Drivez** [comment]
@mphill i added the `react-native-svg` package to the project and it may have solved it, just tested it locally on the device. I will test a new build via Expo as well.

**Comment by Drivez** [comment]
used the commented fix, and added the package mentioned above to solve the issue.
