### ISSUE TITLE
Support for defaultProps will be removed

### ISSUE THREAD

**Issue by Drivez** [HichamELBSI/react-native-body-highlighter#56]
This error now comes as an error 
`Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

Any tips on solving this?

**Comment by HichamELBSI** [comment]
Hi, thanks for the issue. It should be fixed now. Please update to the latest version `3.0.0-beta.7`

**Comment by Drivez** [comment]
thanks, will there be a release for this version?

**Comment by HichamELBSI** [comment]
It has been released already, you can upgrade to : `3.0.0-beta.7`
